# Generated by Django 4.2.7 on 2023-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.item'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[(None, 'No response'), ('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], db_index=True, default=None, max_length=1, null=True),
        ),
    ]
