# Generated by Django 4.2.7 on 2023-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_title_alter_invite_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='party',
        ),
        migrations.RemoveField(
            model_name='partyfile',
            name='party',
        ),
        migrations.AddField(
            model_name='externallink',
            name='parties',
            field=models.ManyToManyField(blank=True, to='api.party'),
        ),
        migrations.AddField(
            model_name='partyfile',
            name='parties',
            field=models.ManyToManyField(blank=True, to='api.party'),
        ),
    ]
