# Generated by Django 4.2.7 on 2023-12-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apiclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterIndexTogether(
            name='apiclient',
            index_together={('api_key', 'active')},
        ),
    ]
