# Generated by Django 4.2.7 on 2023-12-04 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_apiclient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='people',
        ),
        migrations.AddField(
            model_name='allergy',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='allergies',
            field=models.ManyToManyField(blank=True, through='api.Allergy', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient'),
        ),
    ]
