# Generated by Django 4.2.7 on 2023-12-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_allergy_people_allergy_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
