# Generated by Django 4.2.7 on 2023-12-04 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_allergy_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergic_people',
            field=models.ManyToManyField(through='api.Allergy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='max_people',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='closed',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
