# Generated by Django 4.2.7 on 2023-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='show_in_guest_list',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
