# Generated by Django 4.2.7 on 2023-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_invite_show_in_guest_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
