# Generated by Django 4.2.7 on 2023-12-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_message_sent_at_remove_message_sent_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLinkSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_via', models.CharField(blank=True, choices=[('W', 'WhatsApp'), ('S', 'SMS'), ('E', 'Email'), ('T', 'Telegram')], db_index=True, max_length=30, null=True)),
                ('sid', models.CharField(blank=True, max_length=34, null=True)),
                ('error', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Links Sent',
                'index_together': {('person', 'party', 'sent')},
            },
        ),
    ]
