# Generated by Django 4.2.7 on 2023-12-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_personallinksent'),
    ]

    operations = [
        migrations.AddField(
            model_name='personallinksent',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
