# Generated by Django 4.2.7 on 2023-12-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_partyfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyfile',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
