# Generated by Django 4.2.7 on 2023-12-19 13:46

from django.db import migrations


def create_preferences_for_persons(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    Preferences = apps.get_model('api', 'Preferences')

    for person in Person.objects.all():
        Preferences.objects.get_or_create(person=person)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20231219_1330'),
    ]

    operations = [
        migrations.RunPython(create_preferences_for_persons),
    ]
