# Generated by Django 4.2.7 on 2024-01-07 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20231219_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_via', models.CharField(blank=True, choices=[('W', 'WhatsApp'), ('S', 'SMS'), ('E', 'Email'), ('T', 'Telegram')], db_index=True, max_length=30, null=True)),
                ('sid', models.CharField(blank=True, max_length=34, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('error', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Messages Sent',
            },
        ),
        migrations.AlterIndexTogether(
            name='personallinksent',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='personallinksent',
            name='party',
        ),
        migrations.RemoveField(
            model_name='personallinksent',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-due_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='draft',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together={('party', 'due_at', 'draft')},
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
        migrations.DeleteModel(
            name='PersonalLinkSent',
        ),
        migrations.AddField(
            model_name='messagesent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.message'),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.party'),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='messagesent',
            unique_together={('message', 'person', 'party', 'sent_via')},
        ),
        migrations.AlterIndexTogether(
            name='messagesent',
            index_together={('message', 'person', 'party', 'sent')},
        ),
    ]
