# Generated by Django 4.2.7 on 2024-01-09 10:42

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_message_options_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=markdownfield.models.MarkdownField(blank=True, default='', rendered_field='text_rendered'),
        ),
    ]
