# Generated by Django 4.2.7 on 2024-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_threshold',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
