# Generated by Django 4.2.7 on 2024-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_message_send_threshold'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='message',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='autosend',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together={('party', 'due_at', 'draft', 'autosend')},
        ),
    ]
