# Generated by Django 4.2.7 on 2024-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_message_index_together_message_autosend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('text', models.TextField(blank=True, db_index=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('send_threshold', models.DurationField(blank=True, null=True)),
                ('draft', models.BooleanField(db_index=True, default=True)),
                ('autosend', models.BooleanField(db_index=True, default=False)),
                ('friendly_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('variables', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
