# Generated by Django 4.2.7 on 2024-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='sid',
            field=models.CharField(blank=True, editable=False, max_length=34, null=True),
        ),
    ]
