# Generated by Django 4.2.7 on 2024-02-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_messagetemplate_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
