# Generated by Django 4.2.7 on 2024-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_messagetemplate_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='is_default_party_message',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
