# Generated by Django 4.2.7 on 2024-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_messagetemplate_is_default_party_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('UTILITY', 'UTILITY'), ('MARKETING', 'MARKETING'), ('AUTHENTICATION', 'AUTHENTICATION')], db_index=True, default='UTILITY', max_length=30, null=True),
        ),
    ]
