# Generated by Django 4.2.7 on 2024-02-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_messagetemplate_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='rejected',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_SUBMITTED', 'NOT_SUBMITTED'), ('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], db_index=True, default='NOT_SUBMITTED', max_length=25, null=True),
        ),
    ]
