# Generated by Django 4.2.7 on 2024-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_messagetemplate_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='send_delta',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
