# Generated by Django 4.2.7 on 2024-02-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_messagetemplate_send_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='due_at',
        ),
    ]
