# Generated by Django 4.2.7 on 2024-02-02 12:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_messagetemplate_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='variables',
            field=models.JSONField(blank=True, default=api.models._default_variables, null=True),
        ),
    ]
