# Generated by Django 4.2.7 on 2024-02-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_messagetemplate_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.messagetemplate'),
        ),
    ]
