# Generated by Django 4.2.7 on 2024-02-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_message_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['-party__date_and_time', 'person__first_name', 'person__last_name', '-status']},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('party', 'title')},
        ),
    ]
