name: Deploy Django Application

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repository
      uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/biagio/sins-love-and-rainbows
          git pull
          source .venv/bin/activate
          cd src
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart sinsloveandrainbows
          echo "Successful deployment $(date)" >> deployments.txt
